2025-04-02 23:08:45,411 - error_logger - ERROR - log_factory: Traceback (most recent call last):
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/__init__.py", line 43, in get_server_info
    loop.run_until_complete(asyncio.gather(*task_list))
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/CpuPlugin.py", line 14, in process
    content = await executor(host, 'cat /proc/cpuinfo')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zy/CMDB/CMDB_Central_Control/lib/executor/paramiko_executor.py", line 11, in paramiko_executor
    stdin, stdout, stderr = await ssh.exec_command(command)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object tuple can't be used in 'await' expression

2025-04-03 23:56:50,268 - error_logger - ERROR - log_factory: Traceback (most recent call last):
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/CpuPlugin.py", line 12, in process
    raise StopIteration
StopIteration

2025-04-03 23:57:34,403 - error_logger - ERROR - log_factory: Traceback (most recent call last):
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/CpuPlugin.py", line 12, in process
    raise StopIteration
StopIteration

2025-04-06 00:46:23,485 - error_logger - ERROR - log_factory: Traceback (most recent call last):
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/NicPlugin.py", line 21, in process
    response.data = self.parse(content)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/zy/CMDB/CMDB_Central_Control/src/plugins/NicPlugin.py", line 76, in parse
    print(json.dumps(response))
          ^^^^
NameError: name 'json' is not defined

